- name: Install Nginx
  hosts: web
  become: yes
  tasks:
  - name: install Nginx
    ansible.builtin.package:
      name: nginx
      state: presnt
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes  
      