- name: "task level variables"
  hosts: "web"
  vars:
    Cource: "Devops"
    Duration: "120HRS"
    Trainer: "Siva"
  tasks:
    - name: "Play level variables"
      ansible.builtin.debug:
        msg: "I am learning {{Cource}} Duration is {{Duration}} and the trainer is : {{Trainer}}"
    - name: "Play level variables"
      vars:
        Duration: "140HRS"
      ansible.builtin.debug:
       msg: "I am learning {{Cource}} Duration is {{Duration}} and the trainer is : {{Trainer}}"
    - name: "Play level variables"
      ansible.builtin.debug:
        msg: "I am learning {{Cource}} Duration is {{Duration}} and the trainer is : {{Trainer}}"     
         

      
