- name: "File level Variables"
  hosts: "web"
  vars_files:
    - vars.yaml
  tasks:
    - name: "File level Variables"
      ansible.builtin.debug:
        msg: "I am learning {{COURSE}} Duration is {{DURATION}} and the trainer is : {{TRAINER}}"