- name: "prompt level variables"
  hosts: "web"
  vars_prompt:
    - name: "COURSE"
      prompt: "Please enter course name"
      private: false # this is used to display the input over the terminal
    - name: "DURATION"
      prompt: "Please enter duration"
    - name: "TRAINER"
      prompt: "Please enter TRAINER name"
  tasks:
    - name: "Prompt level variable"
      ansible.builtin.debug:
        msg: "I am learning {{COURSE}} Duration is {{DURATION}} and the trainer is : {{TRAINER}}"       
