- name: "datatypes in ansible"
  hosts: local
  connection: local  # No need for username and password when running locally
  vars:
    COURSE: "Devops"  # string
    DURATION: 120  # Number
    TOPICS:  # list
      - Linux
      - Shell
      - Ansible
      - Terraform
    live: true  # boolean
    tools:  # map/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws
  tasks:
    - name: "Show datatypes in ansible"
      ansible.builtin.debug:
        msg: |
          I am learning {{ COURSE }}.
          Duration: {{ DURATION }} hours.
          Topics are: {{ TOPICS | join(', ') }}.
          Live session: {{ live }}.
          Tools: 
            CI: {{ tools.ci }}
            CM: {{ tools.cm }}
            Cloud: {{ tools.cloud }}
