- name: "datatypes in ansible"
  hosts: local
  connection: local # when you are inside the server username,password doesn't required
  vars:
    COURSE: "Devops" #string
    DURATION: 120 #Number
    TOPICS: #list
      - Linux
      - Shell
      - ansible
      - terraform
    live: true #boolean
    tools: #map/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws
  tasks:
    - name: "datatypes in ansible"
      anisble.builtin.debug:
        msg: "i am learning {{COURSE}} duation: {{DURATION}} totics are: {{TOPICS}},{{live}},{{tools}}{{ci}},{{cm}},{{cloud}}"       
