- name : create user
  hosts: web
  become: true
  tasks:
    - name: create user expense
      ansible.builtin.command: id expense
      register: USER
      ignore_errors: true
    - name: print user details
      ansible.builtin.debug:
        msg: "user info {{ USER }}" 
    - name: add user if not present
      ansible.builtin.command: useradd expense
      when: USER.rc != 0 