- name: install nginx
  hosts: web
  become: true
  tasks:
    - name: install nginx if RedHat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat" 
    - name: install nginx if Debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"   
    - name: start Service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes      