- name: filters demo
  hosts: local
  connection: local
  tasks:
  - name: function/filters on ansible
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }} "
  - name: convert to upper
    vars:
      greeting: "Good Morning"
    ansible.builtin.debug:
      msg: " {{greeting | upper}} "     
  - name: convert to upper
    vars:
      greeting: "Good Morning"
    ansible.builtin.debug:
      msg: " {{greeting | lower}} "       
  - name: filter unique numbers
    vars:
      Numbers: [1,2,3,4,3,2,1,5]
    ansible.builtin.debug:
      msg: " {{Numbers | unique}} "  
  - name: filter mix and max
    vars:
      Numbers: [1,2,3,4,3,2,1,5]
    ansible.builtin.debug:
      msg: " min: {{Numbers | min}},max: {{Numbers | max}}  "  
  - name: dict to items
    vars:
      course:
        name: "Devops with AWS"
        Duration: 120
        trainer: "Siva Kumar Reddy"
    ansible.builtin.debug:
      msg: "items are {{ course | dict2items }}"    
