- name: filters demo
  hosts: local
  connection: local
  tasks:
  - name: function/filters on ansible
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }} "
  - name: convert to upper
    vars:
      greeting: "Good Morning"
    ansible.builtin.debug:
      msg: " {{greeting | upper}} "     
  - name: convert to upper
    vars:
      greeting: "Good Morning"
    ansible.builtin.debug:
      msg: " {{greeting | lower}} "       
